name: Release Pipeline for Main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # ✅ Step 2: Test Unitari
  test:
    name: Run Tests 
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Run tests
        run: pytest --cov=nezuki --cov-report=term-missing


  # ✅ Step 4: Build e Publish su PyPI
  build-and-publish:
    name: Build & Publish Package
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packaging tools
        run: pip install setuptools wheel twine

      - name: Build Package
        run: |
          rm -rf dist  # ✅ Pulisce la cartella dist prima di creare il pacchetto
          python setup.py sdist bdist_wheel

      - name: Upload Package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*